# Waqar & Brothers - Daily Account Book
# Main Flask Application (Phase 1)

import os
import sys
import io
import shutil
import sqlite3
import webbrowser
import traceback
from functools import wraps
from datetime import datetime, date, timedelta
from threading import Timer
import pandas as pd
from flask import (Flask, render_template, request, redirect, url_for,
                   session, flash, g, send_file)
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename


def resource_path(relative_path):
    """Get path to bundled resource — works in both normal Python and PyInstaller .exe."""
    if getattr(sys, 'frozen', False):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), relative_path)


def get_base_path():
    """Get the directory where the .exe lives (for user data like accounts.db)."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


# --- App Setup ---
BASE_PATH = get_base_path()
DATABASE = os.path.join(BASE_PATH, 'accounts.db')

app = Flask(
    __name__,
    template_folder=resource_path('templates'),
    static_folder=resource_path('static')
)

# Load secret key from config.py (generated by install.bat)
try:
    if getattr(sys, 'frozen', False):
        # In .exe mode, load config from the directory where .exe lives
        import importlib.util
        config_file = os.path.join(BASE_PATH, 'config.py')
        if os.path.exists(config_file):
            spec = importlib.util.spec_from_file_location('config', config_file)
            config = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(config)
            app.secret_key = config.SECRET_KEY
        else:
            app.secret_key = os.urandom(24)
    else:
        from config import SECRET_KEY
        app.secret_key = SECRET_KEY
except (ImportError, AttributeError):
    app.secret_key = os.urandom(24)

# Session ends when browser closes
app.config['SESSION_PERMANENT'] = False

# Uploads folder for receipt images
UPLOAD_FOLDER = os.path.join(BASE_PATH, 'uploads')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


# --- Database Helper ---
def get_db():
    """Get a database connection for the current request."""
    if 'db' not in g:
        g.db = sqlite3.connect(DATABASE)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(exception):
    """Close the database connection at the end of each request."""
    db = g.pop('db', None)
    if db is not None:
        db.close()


def init_db():
    """Create tables and run migrations if needed. Safe to call on every startup."""
    try:
        conn = sqlite3.connect(DATABASE)
        cursor = conn.cursor()

        # --- Create tables ---
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS users (
                id                   INTEGER PRIMARY KEY AUTOINCREMENT,
                username             TEXT    NOT NULL UNIQUE,
                password             TEXT    NOT NULL,
                must_change_password INTEGER NOT NULL DEFAULT 1,
                failed_attempts      INTEGER NOT NULL DEFAULT 0,
                locked_until         TEXT    DEFAULT NULL
            )
        ''')

        cursor.execute('''
            CREATE TABLE IF NOT EXISTS daily_entries (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                date         TEXT    NOT NULL,
                type         TEXT    NOT NULL,
                amount       INTEGER NOT NULL,
                description  TEXT    NOT NULL,
                notes        TEXT    DEFAULT '',
                is_deleted   INTEGER NOT NULL DEFAULT 0,
                created_at   TEXT    NOT NULL,
                payment_type TEXT    DEFAULT 'cash',
                receipt      TEXT,
                category     TEXT    DEFAULT 'other'
            )
        ''')

        cursor.execute('''
            CREATE TABLE IF NOT EXISTS settings (
                key   TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        ''')

        # --- Migrate: add columns if missing (for databases created before these columns) ---
        cursor.execute('PRAGMA table_info(daily_entries)')
        existing_columns = [row[1] for row in cursor.fetchall()]

        if 'payment_type' not in existing_columns:
            cursor.execute("ALTER TABLE daily_entries ADD COLUMN payment_type TEXT DEFAULT 'cash'")

        if 'receipt' not in existing_columns:
            cursor.execute('ALTER TABLE daily_entries ADD COLUMN receipt TEXT')

        if 'category' not in existing_columns:
            cursor.execute("ALTER TABLE daily_entries ADD COLUMN category TEXT DEFAULT 'other'")

        # --- Indexes ---
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_entries_date
            ON daily_entries(date, is_deleted)
        ''')
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_entries_type
            ON daily_entries(date, type, is_deleted)
        ''')

        # --- Default admin user if users table is empty ---
        cursor.execute('SELECT COUNT(*) FROM users')
        if cursor.fetchone()[0] == 0:
            hashed_password = generate_password_hash('admin123', method='pbkdf2:sha256')
            cursor.execute('''
                INSERT INTO users (username, password, must_change_password, failed_attempts, locked_until)
                VALUES (?, ?, 1, 0, NULL)
            ''', ('admin', hashed_password))

        # --- Default settings ---
        default_settings = [
            ('business_name', 'Waqar & Brothers'),
            ('opening_balance', '0'),
            ('fy_start', '2025-07-01'),
            ('fy_end', '2026-06-30'),
        ]
        for key, value in default_settings:
            cursor.execute('INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)', (key, value))

        conn.commit()
        conn.close()
    except Exception:
        # Log init errors to a file next to the executable/script
        log_path = os.path.join(BASE_PATH, 'init_error.log')
        with open(log_path, 'w') as f:
            f.write(traceback.format_exc())
        raise


# Initialize database on startup
init_db()


@app.context_processor
def inject_business_name():
    """Make business_name available in every template (for navbar branding)."""
    if session.get('user_id'):
        db = get_db()
        name = get_setting(db, 'business_name') or 'Waqar & Brothers'
        return {'business_name': name}
    return {'business_name': 'Waqar & Brothers'}


# --- Login Required Decorator ---
def login_required(f):
    """Redirect to login page if user is not logged in."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function


# --- Debug Error Handler (shows full traceback in browser) ---

@app.errorhandler(Exception)
def handle_exception(e):
    return f"<h2>Error:</h2><pre>{traceback.format_exc()}</pre>", 500


# --- Serve Uploaded Files ---

@app.route('/uploads/<filename>')
@login_required
def uploaded_file(filename):
    """Serve uploaded receipt images."""
    return send_file(os.path.join(app.config['UPLOAD_FOLDER'], filename))


# --- Step 3: Login Routes ---

@app.route('/')
def index():
    """Home page — redirect to daily page if logged in, else to login."""
    if 'user_id' in session:
        return redirect(url_for('daily'))
    return redirect(url_for('login'))


@app.route('/login', methods=['GET', 'POST'])
def login():
    """Show login form (GET) or process login (POST)."""
    if request.method == 'GET':
        return render_template('login.html')

    # POST — process the login
    username = request.form.get('username', '').strip()
    password = request.form.get('password', '')

    if not username or not password:
        flash('Please enter both username and password.', 'error')
        return render_template('login.html')

    db = get_db()

    # Look up the user
    user = db.execute('SELECT * FROM users WHERE username = ?',
                      (username,)).fetchone()

    if user is None:
        flash('Invalid username or password.', 'error')
        return render_template('login.html')

    # Check if the account is locked
    if user['locked_until']:
        locked_until = datetime.strptime(user['locked_until'],
                                         '%Y-%m-%d %H:%M:%S')
        if datetime.now() < locked_until:
            remaining = (locked_until - datetime.now()).seconds // 60 + 1
            flash(f'Account is locked. Try again in {remaining} minute(s).',
                  'error')
            return render_template('login.html')
        else:
            # Lock period expired — reset failed attempts
            db.execute('''UPDATE users
                          SET failed_attempts = 0, locked_until = NULL
                          WHERE id = ?''', (user['id'],))
            db.commit()
            # Re-fetch user after reset
            user = db.execute('SELECT * FROM users WHERE id = ?',
                              (user['id'],)).fetchone()

    # Check the password
    if not check_password_hash(user['password'], password):
        # Wrong password — increment failed attempts
        new_attempts = user['failed_attempts'] + 1

        if new_attempts >= 5:
            # Lock the account for 15 minutes
            lock_time = (datetime.now() + timedelta(minutes=15)).strftime(
                '%Y-%m-%d %H:%M:%S')
            db.execute('''UPDATE users
                          SET failed_attempts = ?, locked_until = ?
                          WHERE id = ?''',
                       (new_attempts, lock_time, user['id']))
            db.commit()
            flash('Too many wrong attempts. Account locked for 15 minutes.',
                  'error')
        else:
            db.execute('UPDATE users SET failed_attempts = ? WHERE id = ?',
                       (new_attempts, user['id']))
            db.commit()
            remaining = 5 - new_attempts
            flash(f'Invalid username or password. {remaining} attempt(s) left.',
                  'error')

        return render_template('login.html')

    # Password is correct — reset failed attempts and log in
    db.execute('''UPDATE users
                  SET failed_attempts = 0, locked_until = NULL
                  WHERE id = ?''', (user['id'],))
    db.commit()

    session['user_id'] = user['id']
    session['username'] = user['username']

    # If must_change_password is set, redirect to change password page
    if user['must_change_password'] == 1:
        return redirect(url_for('change_password'))

    return redirect(url_for('daily'))


@app.route('/logout')
def logout():
    """Clear the session and redirect to login."""
    session.clear()
    flash('You have been logged out.', 'info')
    return redirect(url_for('login'))


# --- Step 4: Change Password ---

@app.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Force password change on first login, or voluntary change."""
    db = get_db()

    # Check if this is a forced change (first login with default password)
    user = db.execute('SELECT must_change_password FROM users WHERE id = ?',
                      (session['user_id'],)).fetchone()
    forced = user['must_change_password'] == 1

    if request.method == 'GET':
        return render_template('change_password.html', forced=forced)

    # POST — process the password change
    new_password = request.form.get('new_password', '')
    confirm_password = request.form.get('confirm_password', '')

    # Validate: minimum 8 characters
    if len(new_password) < 8:
        flash('Password must be at least 8 characters long.', 'error')
        return render_template('change_password.html', forced=forced)

    # Validate: both fields must match
    if new_password != confirm_password:
        flash('Passwords do not match.', 'error')
        return render_template('change_password.html', forced=forced)

    # Hash the new password and update the database
    hashed = generate_password_hash(new_password, method='pbkdf2:sha256')
    db.execute('''UPDATE users
                  SET password = ?, must_change_password = 0
                  WHERE id = ?''',
               (hashed, session['user_id']))
    db.commit()

    flash('Password changed successfully.', 'success')
    return redirect(url_for('daily'))


# --- PKR Currency Formatter ---

def format_pkr(value):
    """Format a number as PKR with South Asian lakh/crore commas.
    Example: 1952413 -> 'PKR 19,52,413'
    """
    if value is None:
        value = 0

    negative = value < 0
    num = abs(value)
    s = str(num)

    if len(s) <= 3:
        formatted = s
    else:
        # Last 3 digits form the first group
        last3 = s[-3:]
        rest = s[:-3]
        # Group the remaining digits in pairs from right to left
        pairs = []
        while rest:
            pairs.append(rest[-2:])
            rest = rest[:-2]
        pairs.reverse()
        formatted = ','.join(pairs) + ',' + last3

    if negative:
        return f'PKR -{formatted}'
    return f'PKR {formatted}'


# Register as a Jinja template filter so templates can use {{ amount|pkr }}
app.jinja_env.filters['pkr'] = format_pkr


def format_monthday(date_str):
    """Format a date string (YYYY-MM-DD) as 'Apr 05'."""
    try:
        d = datetime.strptime(date_str, '%Y-%m-%d')
        return d.strftime('%b %d')
    except (ValueError, TypeError):
        return date_str


# Register as Jinja filter: {{ entry.date|monthday }}
app.jinja_env.filters['monthday'] = format_monthday


# --- Step 5: Daily Page ---

def get_setting(db, key):
    """Get a single value from the settings table."""
    row = db.execute('SELECT value FROM settings WHERE key = ?',
                     (key,)).fetchone()
    return row['value'] if row else None


def get_opening_balance(db, current_date):
    """Calculate the opening balance for a given date.
    Walk back to find the cumulative balance from all prior entries.
    If no prior entries exist, use the opening_balance from settings.
    """
    initial_balance = int(get_setting(db, 'opening_balance') or 0)

    # Sum all recovery and expense entries before this date (non-deleted)
    row = db.execute('''
        SELECT
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS total_recovery,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS total_expenses
        FROM daily_entries
        WHERE date < ? AND is_deleted = 0
    ''', (current_date,)).fetchone()

    return initial_balance + row['total_recovery'] - row['total_expenses']


@app.route('/daily')
@login_required
def daily():
    """Show the daily register page for a given date, with optional monthly filter."""
    db = get_db()

    # --- Search & filter params ---
    search = request.args.get('search', '').strip()
    filter_payment = request.args.get('payment_type', 'all').strip()
    if filter_payment not in ('cash', 'online', 'all'):
        filter_payment = 'all'
    category = request.args.get('category', 'all').strip()
    valid_categories = ('all', 'food', 'transport', 'bank', 'utility', 'zakat', 'other')
    if category not in valid_categories:
        category = 'all'

    # --- Monthly filter ---
    # If month/year provided, show all entries for that month
    month_param = request.args.get('month')
    year_param = request.args.get('year')

    today = date.today()

    if month_param and year_param:
        try:
            selected_month = int(month_param)
            selected_year = int(year_param)
            if not (1 <= selected_month <= 12):
                raise ValueError
            if not (2000 <= selected_year <= 2100):
                raise ValueError
        except (ValueError, TypeError):
            selected_month = today.month
            selected_year = today.year
    else:
        selected_month = None
        selected_year = None

    # Get business name from settings
    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    if selected_month is not None:
        # --- MONTHLY VIEW ---
        month_str = str(selected_month).zfill(2)
        year_str = str(selected_year)

        # First day of selected month — used for opening balance
        first_of_month = f'{year_str}-{month_str}-01'
        opening_balance = get_opening_balance(db, first_of_month)

        # Get all recovery entries for the month (non-deleted)
        recovery_sql = '''
            SELECT id, date, description, amount, notes
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND type = 'recovery' AND is_deleted = 0'''
        recovery_params = [month_str, year_str]
        if search:
            recovery_sql += ' AND description LIKE ?'
            recovery_params.append(f'%{search}%')
        recovery_sql += ' ORDER BY date ASC, id ASC'
        recoveries = db.execute(recovery_sql, recovery_params).fetchall()

        # Get all expense entries for the month (non-deleted)
        expense_sql = '''
            SELECT id, date, description, amount, notes, receipt, category
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND type = 'expense' AND is_deleted = 0'''
        expense_params = [month_str, year_str]
        if search:
            expense_sql += ' AND description LIKE ?'
            expense_params.append(f'%{search}%')
        if filter_payment != 'all':
            expense_sql += ' AND payment_type = ?'
            expense_params.append(filter_payment)
        if category != 'all':
            expense_sql += ' AND category = ?'
            expense_params.append(category)
        expense_sql += ' ORDER BY date ASC, id ASC'
        expenses = db.execute(expense_sql, expense_params).fetchall()

        # Calculate totals
        total_recovery = sum(r['amount'] for r in recoveries)
        total_expenses = sum(e['amount'] for e in expenses)
        closing_balance = opening_balance + total_recovery - total_expenses

        # Display label for the month
        month_name = date(selected_year, selected_month, 1).strftime('%B %Y')

        # Previous and next month for navigation
        if selected_month == 1:
            prev_month, prev_year = 12, selected_year - 1
        else:
            prev_month, prev_year = selected_month - 1, selected_year

        if selected_month == 12:
            next_month, next_year = 1, selected_year + 1
        else:
            next_month, next_year = selected_month + 1, selected_year

        return render_template('daily.html',
                               business_name=business_name,
                               page_date=first_of_month,
                               display_date=month_name,
                               opening_balance=opening_balance,
                               recoveries=recoveries,
                               expenses=expenses,
                               total_recovery=total_recovery,
                               total_expenses=total_expenses,
                               closing_balance=closing_balance,
                               prev_date=None,
                               next_date=None,
                               view_mode='monthly',
                               selected_month=selected_month,
                               selected_year=selected_year,
                               prev_month=prev_month,
                               prev_year=prev_year,
                               next_month=next_month,
                               next_year=next_year,
                               search=search,
                               filter_payment=filter_payment,
                               category_filter=category,
                               current_date=today.isoformat())

    # --- DAILY VIEW (default) ---
    # Get the date from query string, default to today
    date_str = request.args.get('date', today.isoformat())

    # Parse and validate the date
    try:
        page_date = date.fromisoformat(date_str)
    except ValueError:
        page_date = today
        date_str = page_date.isoformat()

    # Format the date for display (e.g., "Tuesday, 01 April 2026")
    display_date = page_date.strftime('%A, %d %B %Y')

    # Calculate opening balance (walk-back logic)
    opening_balance = get_opening_balance(db, date_str)

    # Get today's recovery entries (non-deleted)
    recovery_sql = '''
        SELECT id, description, amount, notes
        FROM daily_entries
        WHERE date = ? AND type = 'recovery' AND is_deleted = 0'''
    recovery_params = [date_str]
    if search:
        recovery_sql += ' AND description LIKE ?'
        recovery_params.append(f'%{search}%')
    recovery_sql += ' ORDER BY id ASC'
    recoveries = db.execute(recovery_sql, recovery_params).fetchall()

    # Get today's expense entries (non-deleted)
    expense_sql = '''
        SELECT id, description, amount, notes, receipt, category
        FROM daily_entries
        WHERE date = ? AND type = 'expense' AND is_deleted = 0'''
    expense_params = [date_str]
    if search:
        expense_sql += ' AND description LIKE ?'
        expense_params.append(f'%{search}%')
    if filter_payment != 'all':
        expense_sql += ' AND payment_type = ?'
        expense_params.append(filter_payment)
    if category != 'all':
        expense_sql += ' AND category = ?'
        expense_params.append(category)
    expense_sql += ' ORDER BY id ASC'
    expenses = db.execute(expense_sql, expense_params).fetchall()

    # Calculate totals
    total_recovery = sum(r['amount'] for r in recoveries)
    total_expenses = sum(e['amount'] for e in expenses)
    closing_balance = opening_balance + total_recovery - total_expenses

    # Previous and next day for navigation
    prev_date = (page_date - timedelta(days=1)).isoformat()
    next_date = (page_date + timedelta(days=1)).isoformat()

    return render_template('daily.html',
                           business_name=business_name,
                           page_date=date_str,
                           display_date=display_date,
                           opening_balance=opening_balance,
                           recoveries=recoveries,
                           expenses=expenses,
                           total_recovery=total_recovery,
                           total_expenses=total_expenses,
                           closing_balance=closing_balance,
                           prev_date=prev_date,
                           next_date=next_date,
                           view_mode='daily',
                           selected_month=page_date.month,
                           selected_year=page_date.year,
                           prev_month=None,
                           prev_year=None,
                           next_month=None,
                           next_year=None,
                           search=search,
                           filter_payment=filter_payment,
                           category_filter=category,
                           current_date=today.isoformat())


# --- Step 6: Add Recovery (and shared entry form/route for Step 7) ---

@app.route('/add-entry-form')
@login_required
def add_entry_form():
    """Show the Add Recovery or Add Expense form."""
    entry_type = request.args.get('type', 'recovery')
    entry_date = request.args.get('date', date.today().isoformat())

    # Validate entry_type
    if entry_type not in ('recovery', 'expense'):
        entry_type = 'recovery'

    return render_template('add_entry.html',
                           entry_type=entry_type,
                           entry_date=entry_date)


@app.route('/add-entry', methods=['POST'])
@login_required
def add_entry():
    """Save a new recovery or expense entry."""
    db = get_db()

    entry_type = request.form.get('type', '').strip()
    entry_date = request.form.get('date', '').strip()
    description = request.form.get('description', '').strip()
    amount_str = request.form.get('amount', '').strip()
    notes = request.form.get('notes', '').strip()
    payment_type = request.form.get('payment_type', 'cash').strip()
    category = request.form.get('category', 'other').strip()

    # Validate payment_type
    if payment_type not in ('cash', 'online'):
        payment_type = 'cash'

    # Validate category (only for expenses)
    valid_categories = ('food', 'transport', 'bank', 'utility', 'zakat', 'other')
    if category not in valid_categories:
        category = 'other'

    # Handle receipt file upload
    receipt_filename = None
    receipt_file = request.files.get('receipt')
    if receipt_file and receipt_file.filename:
        original_name = secure_filename(receipt_file.filename)
        # Add timestamp to avoid duplicates
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        receipt_filename = f'{timestamp}_{original_name}'
        receipt_file.save(os.path.join(app.config['UPLOAD_FOLDER'], receipt_filename))

    # --- Validation ---

    # Type must be recovery or expense
    if entry_type not in ('recovery', 'expense'):
        flash('Invalid entry type.', 'error')
        return redirect(url_for('daily'))

    # Date must be valid
    try:
        parsed_date = date.fromisoformat(entry_date)
    except ValueError:
        flash('Invalid date format.', 'error')
        return redirect(url_for('daily'))

    # Date must not be in the future
    if parsed_date > date.today():
        flash('Future dates are not allowed.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # Description is required
    if not description:
        if entry_type == 'recovery':
            flash('Salesman name is required.', 'error')
        else:
            flash('Description is required.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # Amount must be a positive whole number
    try:
        amount = int(amount_str)
    except (ValueError, TypeError):
        flash('Amount must be a valid number.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    if amount <= 0:
        flash('Amount must be greater than 0.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # --- Save the entry ---
    created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    db.execute('''
        INSERT INTO daily_entries (date, type, amount, description, notes,
                                   is_deleted, created_at, payment_type, receipt, category)
        VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, ?)
    ''', (entry_date, entry_type, amount, description, notes, created_at,
          payment_type, receipt_filename, category))
    db.commit()

    flash(f'{entry_type.capitalize()} entry saved.', 'success')
    return redirect(url_for('daily', date=entry_date))


# --- Step 8: Edit and Delete ---

@app.route('/edit-entry/<int:entry_id>', methods=['GET', 'POST'])
@login_required
def edit_entry(entry_id):
    """Show edit form (GET) or save edited entry (POST)."""
    db = get_db()

    # Look up the entry (must exist and not be deleted)
    entry = db.execute('''SELECT * FROM daily_entries
                          WHERE id = ? AND is_deleted = 0''',
                       (entry_id,)).fetchone()

    if entry is None:
        flash('Entry not found.', 'error')
        return redirect(url_for('daily'))

    if request.method == 'GET':
        return render_template('edit_entry.html', entry=entry)

    # POST — save the edits
    entry_date = request.form.get('date', '').strip()
    description = request.form.get('description', '').strip()
    amount_str = request.form.get('amount', '').strip()
    notes = request.form.get('notes', '').strip()

    # --- Validation (same rules as add) ---

    # Date must be valid
    try:
        parsed_date = date.fromisoformat(entry_date)
    except ValueError:
        flash('Invalid date format.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Date must not be in the future
    if parsed_date > date.today():
        flash('Future dates are not allowed.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Description is required
    if not description:
        if entry['type'] == 'recovery':
            flash('Salesman name is required.', 'error')
        else:
            flash('Description is required.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Amount must be a positive whole number
    try:
        amount = int(amount_str)
    except (ValueError, TypeError):
        flash('Amount must be a valid number.', 'error')
        return render_template('edit_entry.html', entry=entry)

    if amount <= 0:
        flash('Amount must be greater than 0.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # --- Update the entry ---
    db.execute('''UPDATE daily_entries
                  SET date = ?, description = ?, amount = ?, notes = ?
                  WHERE id = ?''',
               (entry_date, description, amount, notes, entry_id))
    db.commit()

    flash('Entry updated.', 'success')
    return redirect(url_for('daily', date=entry_date))


@app.route('/delete-entry/<int:entry_id>', methods=['POST'])
@login_required
def delete_entry(entry_id):
    """Soft delete an entry — set is_deleted = 1, never hard-delete."""
    db = get_db()

    # Look up the entry to get its date for redirect
    entry = db.execute('SELECT date FROM daily_entries WHERE id = ?',
                       (entry_id,)).fetchone()

    if entry is None:
        flash('Entry not found.', 'error')
        return redirect(url_for('daily'))

    # Soft delete — set is_deleted = 1
    db.execute('UPDATE daily_entries SET is_deleted = 1 WHERE id = ?',
               (entry_id,))
    db.commit()

    flash('Entry deleted.', 'info')
    return redirect(url_for('daily', date=entry['date']))


# --- Step 9: Settings Page ---

@app.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    """Show settings form (GET) or save settings (POST)."""
    db = get_db()

    if request.method == 'GET':
        business_name = get_setting(db, 'business_name') or ''
        opening_balance = get_setting(db, 'opening_balance') or '0'
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance)

    # POST — save settings
    business_name = request.form.get('business_name', '').strip()
    opening_balance_str = request.form.get('opening_balance', '').strip()

    # Validate business name is not empty
    if not business_name:
        flash('Business name cannot be empty.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    # Validate opening balance is a valid number
    try:
        opening_balance = int(opening_balance_str)
    except (ValueError, TypeError):
        flash('Opening balance must be a valid number.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    if opening_balance < 0:
        flash('Opening balance cannot be negative.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    # Save using INSERT OR REPLACE (upsert)
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('business_name', business_name))
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('opening_balance', str(opening_balance)))
    db.commit()

    flash('Settings saved.', 'success')
    return redirect(url_for('settings'))


# --- Dashboard ---

@app.route('/dashboard')
@login_required
def dashboard():
    """Show dashboard with totals, monthly breakdown, and best/worst months."""
    db = get_db()

    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    # Overall totals (all non-deleted entries)
    totals = db.execute('''
        SELECT
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS total_income,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS total_expense
        FROM daily_entries
        WHERE is_deleted = 0
    ''').fetchone()

    total_income = totals['total_income']
    total_expense = totals['total_expense']
    net_profit = total_income - total_expense

    # Monthly breakdown — group by year-month
    rows = db.execute('''
        SELECT
            strftime('%Y', date) AS year,
            strftime('%m', date) AS month,
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS income,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS expense
        FROM daily_entries
        WHERE is_deleted = 0
        GROUP BY strftime('%Y', date), strftime('%m', date)
        ORDER BY year ASC, month ASC
    ''').fetchall()

    # Build monthly_data list with profit calculated
    month_names = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    monthly_data = []
    for row in rows:
        m = int(row['month'])
        y = int(row['year'])
        income = row['income']
        expense = row['expense']
        profit = income - expense
        monthly_data.append({
            'year': y,
            'month': m,
            'month_name': month_names[m],
            'label': f"{month_names[m]} {y}",
            'income': income,
            'expense': expense,
            'profit': profit,
        })

    # Best and worst months by profit
    best_month = None
    worst_month = None
    if monthly_data:
        best_month = max(monthly_data, key=lambda x: x['profit'])
        worst_month = min(monthly_data, key=lambda x: x['profit'])

    # Category-wise expense totals (skip categories with 0)
    cat_rows = db.execute('''
        SELECT COALESCE(category, 'other') AS cat, SUM(amount) AS total
        FROM daily_entries
        WHERE type = 'expense' AND is_deleted = 0
        GROUP BY cat
        ORDER BY total DESC
    ''').fetchall()

    category_labels = {
        'food': 'Food / Tea',
        'transport': 'Transport',
        'bank': 'Bank Slip',
        'utility': 'Utility Bill',
        'zakat': 'Zakat / Charity',
        'other': 'Other',
    }
    category_totals = []
    for row in cat_rows:
        if row['total'] > 0:
            category_totals.append({
                'name': category_labels.get(row['cat'], row['cat'].capitalize()),
                'amount': row['total'],
            })

    return render_template('dashboard.html',
                           business_name=business_name,
                           total_income=total_income,
                           total_expense=total_expense,
                           net_profit=net_profit,
                           monthly_data=monthly_data,
                           best_month=best_month,
                           worst_month=worst_month,
                           category_totals=category_totals)


# --- Export to Excel ---

@app.route('/export/excel')
@login_required
def export_excel():
    """Export monthly entries as an Excel (.xlsx) download."""
    db = get_db()
    today = date.today()

    # Get month/year from query params, default to current month
    try:
        month = int(request.args.get('month', today.month))
        year = int(request.args.get('year', today.year))
        if not (1 <= month <= 12):
            raise ValueError
    except (ValueError, TypeError):
        month = today.month
        year = today.year

    month_str = str(month).zfill(2)
    year_str = str(year)

    # Fetch all non-deleted entries for the month
    rows = db.execute('''
        SELECT date, type, description, amount, notes
        FROM daily_entries
        WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
              AND is_deleted = 0
        ORDER BY date ASC, id ASC
    ''', (month_str, year_str)).fetchall()

    # Build data for DataFrame
    data = []
    for row in rows:
        data.append({
            'Date': row['date'],
            'Type': row['type'].capitalize(),
            'Description': row['description'],
            'Amount': row['amount'],
            'Notes': row['notes'] or '',
        })

    df = pd.DataFrame(data, columns=['Date', 'Type', 'Description', 'Amount', 'Notes'])

    # Write to an in-memory Excel file
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Entries')
    output.seek(0)

    # Generate filename like "WaqarBrothers_Apr_2026.xlsx"
    month_name = date(year, month, 1).strftime('%b')
    filename = f'WaqarBrothers_{month_name}_{year}.xlsx'

    return send_file(output,
                     as_attachment=True,
                     download_name=filename,
                     mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')


# --- Database Backup ---

BACKUP_FOLDER = os.path.join(BASE_PATH, 'backups')
os.makedirs(BACKUP_FOLDER, exist_ok=True)


@app.route('/backup')
@login_required
def backup():
    """Create a timestamped backup of the database file."""
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    backup_filename = f'backup_{timestamp}.db'
    backup_path = os.path.join(BACKUP_FOLDER, backup_filename)

    try:
        shutil.copy2(DATABASE, backup_path)
        flash(f'Backup created: {backup_filename}', 'success')
    except Exception as e:
        flash(f'Backup failed: {str(e)}', 'error')

    return redirect(url_for('settings'))


# --- Export to PDF ---

@app.route('/export/pdf')
@login_required
def export_pdf():
    """Export daily or monthly report as a downloadable PDF."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import (SimpleDocTemplate, Table, TableStyle,
                                     Paragraph, Spacer)
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

    db = get_db()
    today = date.today()
    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    # Determine if daily or monthly
    date_param = request.args.get('date')
    month_param = request.args.get('month')
    year_param = request.args.get('year')

    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title2', parent=styles['Title'],
                                  fontSize=18, spaceAfter=4)
    subtitle_style = ParagraphStyle('Sub', parent=styles['Normal'],
                                     fontSize=11, textColor=colors.grey,
                                     spaceAfter=16)
    section_style = ParagraphStyle('Section', parent=styles['Heading2'],
                                    fontSize=13, spaceBefore=16, spaceAfter=8,
                                    textColor=colors.HexColor('#2c3e50'))

    # Table style
    def make_table_style():
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1),
             [colors.white, colors.HexColor('#f8f9fa')]),
        ])

    # Total row style
    def make_total_style():
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ecf0f1')),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('ALIGN', (-1, 0), (-1, 0), 'RIGHT'),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ])

    elements = []

    if date_param:
        # --- DAILY REPORT ---
        try:
            report_date = date.fromisoformat(date_param)
        except ValueError:
            report_date = today
            date_param = today.isoformat()

        display = report_date.strftime('%b %d, %Y')
        elements.append(Paragraph(business_name, title_style))
        elements.append(Paragraph(f'Daily Report &mdash; {display}', subtitle_style))

        opening_balance = get_opening_balance(db, date_param)

        # Opening balance
        elements.append(Paragraph(f'Opening Balance: {format_pkr(opening_balance)}',
                                   styles['Normal']))
        elements.append(Spacer(1, 8))

        # INCOME section
        recoveries = db.execute('''
            SELECT description, amount
            FROM daily_entries
            WHERE date = ? AND type = 'recovery' AND is_deleted = 0
            ORDER BY id ASC
        ''', (date_param,)).fetchall()

        elements.append(Paragraph('Income (Recovery)', section_style))

        if recoveries:
            data = [['#', 'Salesman', 'Amount']]
            for i, r in enumerate(recoveries, 1):
                data.append([str(i), r['description'], format_pkr(r['amount'])])
            t = Table(data, colWidths=[30, 300, 120])
            t.setStyle(make_table_style())
            elements.append(t)

            total_recovery = sum(r['amount'] for r in recoveries)
            tt = Table([['Total Income', format_pkr(total_recovery)]],
                       colWidths=[330, 120])
            tt.setStyle(make_total_style())
            elements.append(tt)
        else:
            elements.append(Paragraph('No recovery entries.', styles['Normal']))
            total_recovery = 0

        elements.append(Spacer(1, 10))

        # EXPENSE section
        expenses = db.execute('''
            SELECT description, amount, payment_type
            FROM daily_entries
            WHERE date = ? AND type = 'expense' AND is_deleted = 0
            ORDER BY id ASC
        ''', (date_param,)).fetchall()

        elements.append(Paragraph('Expenses', section_style))

        if expenses:
            data = [['#', 'Type', 'Description', 'Amount']]
            for i, e in enumerate(expenses, 1):
                ptype = (e['payment_type'] or 'cash').capitalize()
                data.append([str(i), ptype, e['description'],
                             format_pkr(e['amount'])])
            t = Table(data, colWidths=[30, 80, 220, 120])
            t.setStyle(make_table_style())
            elements.append(t)

            total_expenses = sum(e['amount'] for e in expenses)
            tt = Table([['Total Expenses', format_pkr(total_expenses)]],
                       colWidths=[330, 120])
            tt.setStyle(make_total_style())
            elements.append(tt)
        else:
            elements.append(Paragraph('No expense entries.', styles['Normal']))
            total_expenses = 0

        elements.append(Spacer(1, 14))

        # SUMMARY
        net = opening_balance + total_recovery - total_expenses
        elements.append(Paragraph('Summary', section_style))
        summary_data = [
            ['Opening Balance', format_pkr(opening_balance)],
            ['+ Total Recovery', format_pkr(total_recovery)],
            ['- Total Expenses', format_pkr(total_expenses)],
            ['= Closing Balance', format_pkr(net)],
        ]
        st = Table(summary_data, colWidths=[330, 120])
        st.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, -1), (-1, -1), colors.white),
        ]))
        elements.append(st)

        pdf_filename = f'WaqarBrothers_Daily_{date_param}.pdf'

    else:
        # --- MONTHLY REPORT ---
        try:
            month = int(month_param or today.month)
            year = int(year_param or today.year)
            if not (1 <= month <= 12):
                raise ValueError
        except (ValueError, TypeError):
            month = today.month
            year = today.year

        month_str = str(month).zfill(2)
        year_str = str(year)
        month_label = date(year, month, 1).strftime('%B %Y')

        elements.append(Paragraph(business_name, title_style))
        elements.append(Paragraph(f'Monthly Report &mdash; {month_label}',
                                   subtitle_style))

        # Opening balance for the month
        first_of_month = f'{year_str}-{month_str}-01'
        opening_balance = get_opening_balance(db, first_of_month)

        # Fetch all entries for the month grouped by day
        rows = db.execute('''
            SELECT date, type, description, amount, payment_type
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND is_deleted = 0
            ORDER BY date ASC, id ASC
        ''', (month_str, year_str)).fetchall()

        total_income = 0
        total_expense = 0

        if rows:
            data = [['Date', 'Type', 'Description', 'Payment', 'Amount']]
            for row in rows:
                ptype = (row['payment_type'] or 'cash').capitalize()
                entry_type = row['type'].capitalize()
                data.append([
                    row['date'],
                    entry_type,
                    row['description'],
                    ptype,
                    format_pkr(row['amount']),
                ])
                if row['type'] == 'recovery':
                    total_income += row['amount']
                else:
                    total_expense += row['amount']

            t = Table(data, colWidths=[70, 65, 170, 65, 100])
            t.setStyle(make_table_style())
            elements.append(t)
        else:
            elements.append(Paragraph('No entries for this month.',
                                       styles['Normal']))

        elements.append(Spacer(1, 14))

        # SUMMARY
        net = opening_balance + total_income - total_expense
        elements.append(Paragraph('Summary', section_style))
        summary_data = [
            ['Opening Balance', format_pkr(opening_balance)],
            ['Total Income', format_pkr(total_income)],
            ['Total Expenses', format_pkr(total_expense)],
            ['Closing Balance', format_pkr(net)],
        ]
        st = Table(summary_data, colWidths=[330, 120])
        st.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, -1), (-1, -1), colors.white),
        ]))
        elements.append(st)

        month_short = date(year, month, 1).strftime('%b')
        pdf_filename = f'WaqarBrothers_{month_short}_{year}.pdf'

    # Build PDF in memory
    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=A4,
                             leftMargin=20*mm, rightMargin=20*mm,
                             topMargin=20*mm, bottomMargin=20*mm)
    doc.build(elements)
    output.seek(0)

    return send_file(output,
                     as_attachment=True,
                     download_name=pdf_filename,
                     mimetype='application/pdf')


# --- Run the App ---

def open_browser():
    """Open the app in the default browser after a short delay."""
    webbrowser.open('http://127.0.0.1:8000')


if __name__ == '__main__':
    Timer(1, open_browser).start()
    app.run(host='127.0.0.1', port=8000, debug=False, use_reloader=False)
