# Waqar & Brothers - Daily Account Book
# Main Flask Application (Phase 1)

import os
import sys
import io
import shutil
import sqlite3
import webbrowser
import traceback
from functools import wraps
from datetime import datetime, date, timedelta
from threading import Timer
import pandas as pd
from flask import (Flask, render_template, request, redirect, url_for,
                   session, flash, g, send_file, send_from_directory)
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename


def resource_path(relative_path):
    """Get path to a bundled resource that lives inside app/ — works in
    both normal Python and PyInstaller .exe. Used for templates/ and static/."""
    if getattr(sys, 'frozen', False):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), relative_path)


def assets_path():
    """Get the absolute path to the top-level assets/ folder. In dev mode
    this is C:\\WaqarBrothers\\assets (one level above app/). In frozen
    mode it is _MEIPASS/assets (bundled via --add-data assets;assets)."""
    if getattr(sys, 'frozen', False):
        return os.path.join(sys._MEIPASS, 'assets')
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'assets'
    )


def get_base_path():
    """Get the directory where the .exe lives (for user data like accounts.db)."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


# --- App Setup ---
BASE_PATH = get_base_path()
DATABASE = os.path.join(BASE_PATH, 'accounts.db')

app = Flask(
    __name__,
    template_folder=resource_path('templates'),
    static_folder=resource_path('static')
)

# Load secret key from config.py (generated by install.bat)
try:
    if getattr(sys, 'frozen', False):
        # In .exe mode, load config from the directory where .exe lives
        import importlib.util
        config_file = os.path.join(BASE_PATH, 'config.py')
        if os.path.exists(config_file):
            spec = importlib.util.spec_from_file_location('config', config_file)
            config = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(config)
            app.secret_key = config.SECRET_KEY
        else:
            app.secret_key = os.urandom(24)
    else:
        from config import SECRET_KEY
        app.secret_key = SECRET_KEY
except (ImportError, AttributeError):
    app.secret_key = os.urandom(24)

# Session ends when browser closes
app.config['SESSION_PERMANENT'] = False

# Cache /static assets aggressively (1 year). Flask appends ?v=<mtime> to
# url_for('static', ...) URLs automatically, so edited CSS/JS still
# invalidates correctly — users never see stale files.
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 31536000

# Uploads folder for receipt images
UPLOAD_FOLDER = os.path.join(BASE_PATH, 'uploads')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Top-level assets folder (logos, icons, brand art). Resolved once at
# startup so every request hits a cached path.
ASSETS_FOLDER = assets_path()


@app.route('/assets/<path:filename>')
def assets(filename):
    """Serve files from the top-level assets/ folder.
    Works in both dev (C:\\WaqarBrothers\\assets) and frozen EXE
    (_MEIPASS/assets, bundled via --add-data assets;assets)."""
    return send_from_directory(ASSETS_FOLDER, filename)


# --- Database Helper ---
def get_db():
    """Get a database connection for the current request."""
    if 'db' not in g:
        g.db = sqlite3.connect(DATABASE)
        g.db.row_factory = sqlite3.Row
        # synchronous=NORMAL is per-connection and must be set here.
        # Safe with WAL mode; still fsyncs at checkpoint boundaries so
        # a crash cannot corrupt the database — only the very last
        # in-flight transaction can be lost. That trade is fine for a
        # single-user desktop accounting app.
        g.db.execute('PRAGMA synchronous = NORMAL')
    return g.db


@app.teardown_appcontext
def close_db(exception):
    """Close the database connection at the end of each request."""
    db = g.pop('db', None)
    if db is not None:
        db.close()


def init_db():
    """Create tables and run migrations if needed. Safe to call on every startup."""
    try:
        conn = sqlite3.connect(DATABASE)
        cursor = conn.cursor()

        # --- Create tables ---
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS users (
                id                   INTEGER PRIMARY KEY AUTOINCREMENT,
                username             TEXT    NOT NULL UNIQUE,
                password             TEXT    NOT NULL,
                must_change_password INTEGER NOT NULL DEFAULT 1,
                failed_attempts      INTEGER NOT NULL DEFAULT 0,
                locked_until         TEXT    DEFAULT NULL
            )
        ''')

        cursor.execute('''
            CREATE TABLE IF NOT EXISTS daily_entries (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                date         TEXT    NOT NULL,
                type         TEXT    NOT NULL,
                amount       INTEGER NOT NULL,
                description  TEXT    NOT NULL,
                notes        TEXT    DEFAULT '',
                is_deleted   INTEGER NOT NULL DEFAULT 0,
                created_at   TEXT    NOT NULL,
                payment_type TEXT    DEFAULT 'cash',
                receipt      TEXT,
                category     TEXT    DEFAULT 'other'
            )
        ''')

        cursor.execute('''
            CREATE TABLE IF NOT EXISTS settings (
                key   TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        ''')

        # --- Migrate: add columns if missing (for databases created before these columns) ---
        cursor.execute('PRAGMA table_info(daily_entries)')
        existing_columns = [row[1] for row in cursor.fetchall()]

        if 'payment_type' not in existing_columns:
            cursor.execute("ALTER TABLE daily_entries ADD COLUMN payment_type TEXT DEFAULT 'cash'")

        if 'receipt' not in existing_columns:
            cursor.execute('ALTER TABLE daily_entries ADD COLUMN receipt TEXT')

        if 'category' not in existing_columns:
            cursor.execute("ALTER TABLE daily_entries ADD COLUMN category TEXT DEFAULT 'other'")

        # --- Indexes ---
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_entries_date
            ON daily_entries(date, is_deleted)
        ''')
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_entries_type
            ON daily_entries(date, type, is_deleted)
        ''')
        cursor.execute('''
            CREATE INDEX IF NOT EXISTS idx_entries_category
            ON daily_entries(category, is_deleted)
        ''')

        # --- Persistent PRAGMAs ---
        # WAL is a database-level setting — once set, it sticks across
        # restarts and is recorded in the DB file itself. Better write
        # concurrency, and readers never block writers. Safe on a local
        # Windows filesystem for a single-user desktop app.
        cursor.execute('PRAGMA journal_mode = WAL')

        # --- Default admin user if users table is empty ---
        cursor.execute('SELECT COUNT(*) FROM users')
        if cursor.fetchone()[0] == 0:
            hashed_password = generate_password_hash('admin123', method='pbkdf2:sha256')
            cursor.execute('''
                INSERT INTO users (username, password, must_change_password, failed_attempts, locked_until)
                VALUES (?, ?, 1, 0, NULL)
            ''', ('admin', hashed_password))

        # --- Default settings ---
        default_settings = [
            ('business_name', 'Waqar & Brothers'),
            ('opening_balance', '0'),
            ('fy_start', '2025-07-01'),
            ('fy_end', '2026-06-30'),
        ]
        for key, value in default_settings:
            cursor.execute('INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)', (key, value))

        conn.commit()
        conn.close()
    except Exception:
        # Log init errors to a file next to the executable/script
        log_path = os.path.join(BASE_PATH, 'init_error.log')
        with open(log_path, 'w') as f:
            f.write(traceback.format_exc())
        raise


# Initialize database on startup
init_db()


@app.context_processor
def inject_business_name():
    """Make business_name available in every template (for navbar branding)."""
    if session.get('user_id'):
        db = get_db()
        name = get_setting(db, 'business_name') or 'Waqar & Brothers'
        return {'business_name': name}
    return {'business_name': 'Waqar & Brothers'}


# --- Login Required Decorator ---
def login_required(f):
    """Redirect to login page if user is not logged in."""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function


# --- Debug Error Handler (shows full traceback in browser) ---

@app.errorhandler(Exception)
def handle_exception(e):
    return f"<h2>Error:</h2><pre>{traceback.format_exc()}</pre>", 500


# --- Serve Uploaded Files ---

@app.route('/uploads/<filename>')
@login_required
def uploaded_file(filename):
    """Serve uploaded receipt images."""
    return send_file(os.path.join(app.config['UPLOAD_FOLDER'], filename))


# --- Step 3: Login Routes ---

@app.route('/')
def index():
    """Home page — redirect to daily page if logged in, else to login."""
    if 'user_id' in session:
        return redirect(url_for('daily'))
    return redirect(url_for('login'))


@app.route('/login', methods=['GET', 'POST'])
def login():
    """Show login form (GET) or process login (POST)."""
    if request.method == 'GET':
        return render_template('login.html')

    # POST — process the login
    username = request.form.get('username', '').strip()
    password = request.form.get('password', '')

    if not username or not password:
        flash('Please enter both username and password.', 'error')
        return render_template('login.html')

    db = get_db()

    # Look up the user
    user = db.execute('SELECT * FROM users WHERE username = ?',
                      (username,)).fetchone()

    if user is None:
        flash('Invalid username or password.', 'error')
        return render_template('login.html')

    # Check if the account is locked
    if user['locked_until']:
        locked_until = datetime.strptime(user['locked_until'],
                                         '%Y-%m-%d %H:%M:%S')
        if datetime.now() < locked_until:
            remaining = (locked_until - datetime.now()).seconds // 60 + 1
            flash(f'Account is locked. Try again in {remaining} minute(s).',
                  'error')
            return render_template('login.html')
        else:
            # Lock period expired — reset failed attempts
            db.execute('''UPDATE users
                          SET failed_attempts = 0, locked_until = NULL
                          WHERE id = ?''', (user['id'],))
            db.commit()
            # Re-fetch user after reset
            user = db.execute('SELECT * FROM users WHERE id = ?',
                              (user['id'],)).fetchone()

    # Check the password
    if not check_password_hash(user['password'], password):
        # Wrong password — increment failed attempts
        new_attempts = user['failed_attempts'] + 1

        if new_attempts >= 5:
            # Lock the account for 15 minutes
            lock_time = (datetime.now() + timedelta(minutes=15)).strftime(
                '%Y-%m-%d %H:%M:%S')
            db.execute('''UPDATE users
                          SET failed_attempts = ?, locked_until = ?
                          WHERE id = ?''',
                       (new_attempts, lock_time, user['id']))
            db.commit()
            flash('Too many wrong attempts. Account locked for 15 minutes.',
                  'error')
        else:
            db.execute('UPDATE users SET failed_attempts = ? WHERE id = ?',
                       (new_attempts, user['id']))
            db.commit()
            remaining = 5 - new_attempts
            flash(f'Invalid username or password. {remaining} attempt(s) left.',
                  'error')

        return render_template('login.html')

    # Password is correct — reset failed attempts and log in
    db.execute('''UPDATE users
                  SET failed_attempts = 0, locked_until = NULL
                  WHERE id = ?''', (user['id'],))
    db.commit()

    session['user_id'] = user['id']
    session['username'] = user['username']

    # If must_change_password is set, redirect to change password page
    if user['must_change_password'] == 1:
        return redirect(url_for('change_password'))

    return redirect(url_for('daily'))


@app.route('/logout')
def logout():
    """Clear the session and redirect to login."""
    session.clear()
    flash('You have been logged out.', 'info')
    return redirect(url_for('login'))


# --- Step 4: Change Password ---

@app.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Force password change on first login, or voluntary change."""
    db = get_db()

    # Check if this is a forced change (first login with default password)
    user = db.execute('SELECT must_change_password FROM users WHERE id = ?',
                      (session['user_id'],)).fetchone()
    forced = user['must_change_password'] == 1

    if request.method == 'GET':
        return render_template('change_password.html', forced=forced)

    # POST — process the password change
    new_password = request.form.get('new_password', '')
    confirm_password = request.form.get('confirm_password', '')

    # Validate: minimum 8 characters
    if len(new_password) < 8:
        flash('Password must be at least 8 characters long.', 'error')
        return render_template('change_password.html', forced=forced)

    # Validate: both fields must match
    if new_password != confirm_password:
        flash('Passwords do not match.', 'error')
        return render_template('change_password.html', forced=forced)

    # Hash the new password and update the database
    hashed = generate_password_hash(new_password, method='pbkdf2:sha256')
    db.execute('''UPDATE users
                  SET password = ?, must_change_password = 0
                  WHERE id = ?''',
               (hashed, session['user_id']))
    db.commit()

    flash('Password changed successfully.', 'success')
    return redirect(url_for('daily'))


# --- PKR Currency Formatter ---

def format_pkr(value):
    """Format a number as Rs. with South Asian lakh/crore commas.
    Example: 1952413 -> 'Rs. 19,52,413'
    """
    if value is None:
        value = 0

    negative = value < 0
    num = abs(value)
    s = str(num)

    if len(s) <= 3:
        formatted = s
    else:
        # Last 3 digits form the first group
        last3 = s[-3:]
        rest = s[:-3]
        # Group the remaining digits in pairs from right to left
        pairs = []
        while rest:
            pairs.append(rest[-2:])
            rest = rest[:-2]
        pairs.reverse()
        formatted = ','.join(pairs) + ',' + last3

    if negative:
        return f'Rs. -{formatted}'
    return f'Rs. {formatted}'


# Register as a Jinja template filter so templates can use {{ amount|pkr }}
app.jinja_env.filters['pkr'] = format_pkr


def format_monthday(date_str):
    """Format a date string (YYYY-MM-DD) as 'Apr 05'."""
    try:
        d = datetime.strptime(date_str, '%Y-%m-%d')
        return d.strftime('%b %d')
    except (ValueError, TypeError):
        return date_str


# Register as Jinja filter: {{ entry.date|monthday }}
app.jinja_env.filters['monthday'] = format_monthday


# --- Step 5: Daily Page ---

def get_setting(db, key):
    """Get a single value from the settings table."""
    row = db.execute('SELECT value FROM settings WHERE key = ?',
                     (key,)).fetchone()
    return row['value'] if row else None


def get_opening_balance(db, current_date):
    """Calculate the opening balance for a given date.
    Walk back to find the cumulative balance from all prior entries.
    If no prior entries exist, use the opening_balance from settings.
    """
    initial_balance = int(get_setting(db, 'opening_balance') or 0)

    # Sum all recovery and expense entries before this date (non-deleted)
    row = db.execute('''
        SELECT
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS total_recovery,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS total_expenses
        FROM daily_entries
        WHERE date < ? AND is_deleted = 0
    ''', (current_date,)).fetchone()

    return initial_balance + row['total_recovery'] - row['total_expenses']


@app.route('/daily')
@login_required
def daily():
    """Show the daily register page for a given date, with optional monthly filter."""
    db = get_db()

    # --- Search & filter params ---
    search = request.args.get('search', '').strip()
    filter_payment = request.args.get('payment_type', 'all').strip()
    if filter_payment not in ('cash', 'online', 'all'):
        filter_payment = 'all'
    category = request.args.get('category', 'all').strip()
    valid_categories = ('all', 'food', 'transport', 'bank', 'utility', 'zakat', 'other')
    if category not in valid_categories:
        category = 'all'

    # --- Monthly filter ---
    # If month/year provided, show all entries for that month
    month_param = request.args.get('month')
    year_param = request.args.get('year')

    today = date.today()

    if month_param and year_param:
        try:
            selected_month = int(month_param)
            selected_year = int(year_param)
            if not (1 <= selected_month <= 12):
                raise ValueError
            if not (2000 <= selected_year <= 2100):
                raise ValueError
        except (ValueError, TypeError):
            selected_month = today.month
            selected_year = today.year
    else:
        selected_month = None
        selected_year = None

    # Get business name from settings
    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    if selected_month is not None:
        # --- MONTHLY VIEW ---
        month_str = str(selected_month).zfill(2)
        year_str = str(selected_year)

        # First day of selected month — used for opening balance
        first_of_month = f'{year_str}-{month_str}-01'
        opening_balance = get_opening_balance(db, first_of_month)

        # Get all recovery entries for the month (non-deleted)
        recovery_sql = '''
            SELECT id, date, description, amount, notes
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND type = 'recovery' AND is_deleted = 0'''
        recovery_params = [month_str, year_str]
        if search:
            recovery_sql += ' AND description LIKE ?'
            recovery_params.append(f'%{search}%')
        recovery_sql += ' ORDER BY date ASC, id ASC'
        recoveries = db.execute(recovery_sql, recovery_params).fetchall()

        # Get all expense entries for the month (non-deleted)
        expense_sql = '''
            SELECT id, date, description, amount, notes, receipt, category
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND type = 'expense' AND is_deleted = 0'''
        expense_params = [month_str, year_str]
        if search:
            expense_sql += ' AND description LIKE ?'
            expense_params.append(f'%{search}%')
        if filter_payment != 'all':
            expense_sql += ' AND payment_type = ?'
            expense_params.append(filter_payment)
        if category != 'all':
            expense_sql += ' AND category = ?'
            expense_params.append(category)
        expense_sql += ' ORDER BY date ASC, id ASC'
        expenses = db.execute(expense_sql, expense_params).fetchall()

        # Calculate totals
        total_recovery = sum(r['amount'] for r in recoveries)
        total_expenses = sum(e['amount'] for e in expenses)
        closing_balance = opening_balance + total_recovery - total_expenses

        # Display label for the month
        month_name = date(selected_year, selected_month, 1).strftime('%B %Y')

        # Previous and next month for navigation
        if selected_month == 1:
            prev_month, prev_year = 12, selected_year - 1
        else:
            prev_month, prev_year = selected_month - 1, selected_year

        if selected_month == 12:
            next_month, next_year = 1, selected_year + 1
        else:
            next_month, next_year = selected_month + 1, selected_year

        return render_template('daily.html',
                               business_name=business_name,
                               page_date=first_of_month,
                               display_date=month_name,
                               opening_balance=opening_balance,
                               recoveries=recoveries,
                               expenses=expenses,
                               total_recovery=total_recovery,
                               total_expenses=total_expenses,
                               closing_balance=closing_balance,
                               prev_date=None,
                               next_date=None,
                               view_mode='monthly',
                               selected_month=selected_month,
                               selected_year=selected_year,
                               prev_month=prev_month,
                               prev_year=prev_year,
                               next_month=next_month,
                               next_year=next_year,
                               search=search,
                               filter_payment=filter_payment,
                               category_filter=category,
                               current_date=today.isoformat(),
                               is_closed=False,
                               is_reopened=False,
                               reopen_time=None)

    # --- DAILY VIEW (default) ---
    # Get the date from query string, default to today
    date_str = request.args.get('date', today.isoformat())

    # Parse and validate the date
    try:
        page_date = date.fromisoformat(date_str)
    except ValueError:
        page_date = today
        date_str = page_date.isoformat()

    # Format the date for display (e.g., "Tuesday, 01 April 2026")
    display_date = page_date.strftime('%A, %d %B %Y')

    # Calculate opening balance (walk-back logic)
    opening_balance = get_opening_balance(db, date_str)

    # Get today's recovery entries (non-deleted)
    recovery_sql = '''
        SELECT id, description, amount, notes
        FROM daily_entries
        WHERE date = ? AND type = 'recovery' AND is_deleted = 0'''
    recovery_params = [date_str]
    if search:
        recovery_sql += ' AND description LIKE ?'
        recovery_params.append(f'%{search}%')
    recovery_sql += ' ORDER BY id ASC'
    recoveries = db.execute(recovery_sql, recovery_params).fetchall()

    # Get today's expense entries (non-deleted)
    expense_sql = '''
        SELECT id, description, amount, notes, receipt, category
        FROM daily_entries
        WHERE date = ? AND type = 'expense' AND is_deleted = 0'''
    expense_params = [date_str]
    if search:
        expense_sql += ' AND description LIKE ?'
        expense_params.append(f'%{search}%')
    if filter_payment != 'all':
        expense_sql += ' AND payment_type = ?'
        expense_params.append(filter_payment)
    if category != 'all':
        expense_sql += ' AND category = ?'
        expense_params.append(category)
    expense_sql += ' ORDER BY id ASC'
    expenses = db.execute(expense_sql, expense_params).fetchall()

    # Calculate totals
    total_recovery = sum(r['amount'] for r in recoveries)
    total_expenses = sum(e['amount'] for e in expenses)
    closing_balance = opening_balance + total_recovery - total_expenses

    # Previous and next day for navigation
    prev_date = (page_date - timedelta(days=1)).isoformat()
    next_date = (page_date + timedelta(days=1)).isoformat()

    return render_template('daily.html',
                           business_name=business_name,
                           page_date=date_str,
                           display_date=display_date,
                           opening_balance=opening_balance,
                           recoveries=recoveries,
                           expenses=expenses,
                           total_recovery=total_recovery,
                           total_expenses=total_expenses,
                           closing_balance=closing_balance,
                           prev_date=prev_date,
                           next_date=next_date,
                           view_mode='daily',
                           selected_month=page_date.month,
                           selected_year=page_date.year,
                           prev_month=None,
                           prev_year=None,
                           next_month=None,
                           next_year=None,
                           search=search,
                           filter_payment=filter_payment,
                           category_filter=category,
                           current_date=today.isoformat(),
                           is_closed=is_day_closed(date_str),
                           is_reopened=is_day_reopened(date_str),
                           reopen_time=get_reopen_time(date_str))


# --- Step 6: Add Recovery (and shared entry form/route for Step 7) ---

@app.route('/add-entry-form')
@login_required
def add_entry_form():
    """Show the Add Recovery or Add Expense form."""
    entry_type = request.args.get('type', 'recovery')
    entry_date = request.args.get('date', date.today().isoformat())

    # Validate entry_type
    if entry_type not in ('recovery', 'expense'):
        entry_type = 'recovery'

    return render_template('add_entry.html',
                           entry_type=entry_type,
                           entry_date=entry_date)


@app.route('/add-entry', methods=['POST'])
@login_required
def add_entry():
    """Save a new recovery or expense entry."""
    db = get_db()

    entry_type = request.form.get('type', '').strip()
    entry_date = request.form.get('date', '').strip()
    description = request.form.get('description', '').strip()
    amount_str = request.form.get('amount', '').strip()
    notes = request.form.get('notes', '').strip()
    payment_type = request.form.get('payment_type', 'cash').strip()
    category = request.form.get('category', 'other').strip()

    # Validate payment_type
    if payment_type not in ('cash', 'online'):
        payment_type = 'cash'

    # Validate category (only for expenses)
    valid_categories = ('food', 'transport', 'bank', 'utility', 'zakat', 'other')
    if category not in valid_categories:
        category = 'other'

    # Handle receipt file upload
    receipt_filename = None
    receipt_file = request.files.get('receipt')
    if receipt_file and receipt_file.filename:
        original_name = secure_filename(receipt_file.filename)
        # Add timestamp to avoid duplicates
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        receipt_filename = f'{timestamp}_{original_name}'
        receipt_file.save(os.path.join(app.config['UPLOAD_FOLDER'], receipt_filename))

    # --- Validation ---

    # Type must be recovery or expense
    if entry_type not in ('recovery', 'expense'):
        flash('Invalid entry type.', 'error')
        return redirect(url_for('daily'))

    # Date must be valid
    try:
        parsed_date = date.fromisoformat(entry_date)
    except ValueError:
        flash('Invalid date format.', 'error')
        return redirect(url_for('daily'))

    # Date must not be in the future
    if parsed_date > date.today():
        flash('Future dates are not allowed.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # Block if the target day is already closed
    if is_day_closed(entry_date):
        flash('This day is closed. No changes allowed.', 'error')
        return redirect(url_for('daily', date=entry_date))

    # Description is required
    if not description:
        if entry_type == 'recovery':
            flash('Salesman name is required.', 'error')
        else:
            flash('Description is required.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # Amount must be a positive whole number
    try:
        amount = int(amount_str)
    except (ValueError, TypeError):
        flash('Amount must be a valid number.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    if amount <= 0:
        flash('Amount must be greater than 0.', 'error')
        return redirect(url_for('add_entry_form', type=entry_type,
                                date=entry_date))

    # --- Save the entry ---
    created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    db.execute('''
        INSERT INTO daily_entries (date, type, amount, description, notes,
                                   is_deleted, created_at, payment_type, receipt, category)
        VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, ?)
    ''', (entry_date, entry_type, amount, description, notes, created_at,
          payment_type, receipt_filename, category))
    db.commit()

    flash(f'{entry_type.capitalize()} entry saved.', 'success')
    return redirect(url_for('daily', date=entry_date))


# --- Step 8: Edit and Delete ---

@app.route('/edit-entry/<int:entry_id>', methods=['GET', 'POST'])
@login_required
def edit_entry(entry_id):
    """Show edit form (GET) or save edited entry (POST)."""
    db = get_db()

    # Look up the entry (must exist and not be deleted)
    entry = db.execute('''SELECT * FROM daily_entries
                          WHERE id = ? AND is_deleted = 0''',
                       (entry_id,)).fetchone()

    if entry is None:
        flash('Entry not found.', 'error')
        return redirect(url_for('daily'))

    # Block edits if the entry's own day is closed (GET or POST)
    if is_day_closed(entry['date']):
        flash('This day is closed. No changes allowed.', 'error')
        return redirect(url_for('daily', date=entry['date']))

    if request.method == 'GET':
        return render_template('edit_entry.html', entry=entry)

    # POST — save the edits
    entry_date = request.form.get('date', '').strip()
    description = request.form.get('description', '').strip()
    amount_str = request.form.get('amount', '').strip()
    notes = request.form.get('notes', '').strip()

    # Also block if user tries to move the entry into a closed day
    if is_day_closed(entry_date):
        flash('This day is closed. No changes allowed.', 'error')
        return redirect(url_for('daily', date=entry_date))

    # --- Validation (same rules as add) ---

    # Date must be valid
    try:
        parsed_date = date.fromisoformat(entry_date)
    except ValueError:
        flash('Invalid date format.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Date must not be in the future
    if parsed_date > date.today():
        flash('Future dates are not allowed.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Description is required
    if not description:
        if entry['type'] == 'recovery':
            flash('Salesman name is required.', 'error')
        else:
            flash('Description is required.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # Amount must be a positive whole number
    try:
        amount = int(amount_str)
    except (ValueError, TypeError):
        flash('Amount must be a valid number.', 'error')
        return render_template('edit_entry.html', entry=entry)

    if amount <= 0:
        flash('Amount must be greater than 0.', 'error')
        return render_template('edit_entry.html', entry=entry)

    # --- Update the entry ---
    db.execute('''UPDATE daily_entries
                  SET date = ?, description = ?, amount = ?, notes = ?
                  WHERE id = ?''',
               (entry_date, description, amount, notes, entry_id))
    db.commit()

    flash('Entry updated.', 'success')
    return redirect(url_for('daily', date=entry_date))


@app.route('/delete-entry/<int:entry_id>', methods=['POST'])
@login_required
def delete_entry(entry_id):
    """Soft delete an entry — set is_deleted = 1, never hard-delete."""
    db = get_db()

    # Look up the entry to get its date for redirect
    entry = db.execute('SELECT date FROM daily_entries WHERE id = ?',
                       (entry_id,)).fetchone()

    if entry is None:
        flash('Entry not found.', 'error')
        return redirect(url_for('daily'))

    # Block delete if the entry's day is already closed
    if is_day_closed(entry['date']):
        flash('This day is closed. No changes allowed.', 'error')
        return redirect(url_for('daily', date=entry['date']))

    # Soft delete — set is_deleted = 1
    db.execute('UPDATE daily_entries SET is_deleted = 1 WHERE id = ?',
               (entry_id,))
    db.commit()

    flash('Entry deleted.', 'info')
    return redirect(url_for('daily', date=entry['date']))


# --- Step 9: Settings Page ---

@app.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    """Show settings form (GET) or save settings (POST)."""
    db = get_db()

    if request.method == 'GET':
        business_name = get_setting(db, 'business_name') or ''
        opening_balance = get_setting(db, 'opening_balance') or '0'
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance)

    # POST — save settings
    business_name = request.form.get('business_name', '').strip()
    opening_balance_str = request.form.get('opening_balance', '').strip()

    # Validate business name is not empty
    if not business_name:
        flash('Business name cannot be empty.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    # Validate opening balance is a valid number
    try:
        opening_balance = int(opening_balance_str)
    except (ValueError, TypeError):
        flash('Opening balance must be a valid number.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    if opening_balance < 0:
        flash('Opening balance cannot be negative.', 'error')
        return render_template('settings.html',
                               business_name=business_name,
                               opening_balance=opening_balance_str)

    # Save using INSERT OR REPLACE (upsert)
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('business_name', business_name))
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('opening_balance', str(opening_balance)))
    db.commit()

    flash('Settings saved.', 'success')
    return redirect(url_for('settings'))


# --- Dashboard ---

@app.route('/dashboard')
@login_required
def dashboard():
    """Show dashboard with totals, monthly breakdown, and best/worst months."""
    db = get_db()

    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    # Overall totals (all non-deleted entries)
    totals = db.execute('''
        SELECT
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS total_income,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS total_expense
        FROM daily_entries
        WHERE is_deleted = 0
    ''').fetchone()

    total_income = totals['total_income']
    total_expense = totals['total_expense']
    net_profit = total_income - total_expense

    # Monthly breakdown — group by year-month
    rows = db.execute('''
        SELECT
            strftime('%Y', date) AS year,
            strftime('%m', date) AS month,
            COALESCE(SUM(CASE WHEN type = 'recovery' THEN amount ELSE 0 END), 0)
                AS income,
            COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)
                AS expense
        FROM daily_entries
        WHERE is_deleted = 0
        GROUP BY strftime('%Y', date), strftime('%m', date)
        ORDER BY year ASC, month ASC
    ''').fetchall()

    # Build monthly_data list with profit calculated
    month_names = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    monthly_data = []
    for row in rows:
        m = int(row['month'])
        y = int(row['year'])
        income = row['income']
        expense = row['expense']
        profit = income - expense
        monthly_data.append({
            'year': y,
            'month': m,
            'month_name': month_names[m],
            'label': f"{month_names[m]} {y}",
            'income': income,
            'expense': expense,
            'profit': profit,
        })

    # Best and worst months by profit
    best_month = None
    worst_month = None
    if monthly_data:
        best_month = max(monthly_data, key=lambda x: x['profit'])
        worst_month = min(monthly_data, key=lambda x: x['profit'])

    # Category-wise expense totals (skip categories with 0)
    cat_rows = db.execute('''
        SELECT COALESCE(category, 'other') AS cat, SUM(amount) AS total
        FROM daily_entries
        WHERE type = 'expense' AND is_deleted = 0
        GROUP BY cat
        ORDER BY total DESC
    ''').fetchall()

    category_labels = {
        'food': 'Food / Tea',
        'transport': 'Transport',
        'bank': 'Bank Slip',
        'utility': 'Utility Bill',
        'zakat': 'Zakat / Charity',
        'other': 'Other',
    }
    category_totals = []
    for row in cat_rows:
        if row['total'] > 0:
            category_totals.append({
                'name': category_labels.get(row['cat'], row['cat'].capitalize()),
                'amount': row['total'],
            })

    return render_template('dashboard.html',
                           business_name=business_name,
                           total_income=total_income,
                           total_expense=total_expense,
                           net_profit=net_profit,
                           monthly_data=monthly_data,
                           best_month=best_month,
                           worst_month=worst_month,
                           category_totals=category_totals)


# --- Export to Excel ---

@app.route('/export/excel')
@login_required
def export_excel():
    """Export monthly entries as an Excel (.xlsx) download."""
    db = get_db()
    today = date.today()

    # Get month/year from query params, default to current month
    try:
        month = int(request.args.get('month', today.month))
        year = int(request.args.get('year', today.year))
        if not (1 <= month <= 12):
            raise ValueError
    except (ValueError, TypeError):
        month = today.month
        year = today.year

    month_str = str(month).zfill(2)
    year_str = str(year)

    # Fetch all non-deleted entries for the month
    rows = db.execute('''
        SELECT date, type, description, amount, notes
        FROM daily_entries
        WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
              AND is_deleted = 0
        ORDER BY date ASC, id ASC
    ''', (month_str, year_str)).fetchall()

    # Build data for DataFrame
    data = []
    for row in rows:
        data.append({
            'Date': row['date'],
            'Type': row['type'].capitalize(),
            'Description': row['description'],
            'Amount': row['amount'],
            'Notes': row['notes'] or '',
        })

    df = pd.DataFrame(data, columns=['Date', 'Type', 'Description', 'Amount', 'Notes'])

    # Write to an in-memory Excel file
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Entries')
    output.seek(0)

    # Generate filename like "WaqarBrothers_Apr_2026.xlsx"
    month_name = date(year, month, 1).strftime('%b')
    filename = f'WaqarBrothers_{month_name}_{year}.xlsx'

    return send_file(output,
                     as_attachment=True,
                     download_name=filename,
                     mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')


# --- Database Backup ---

if getattr(sys, 'frozen', False):
    BASE_DIR = BASE_PATH                     # EXE sits at project root already
else:
    BASE_DIR = os.path.dirname(BASE_PATH)    # dev: app/ → WaqarBrothers/
BACKUP_FOLDER = os.path.join(BASE_DIR, 'backups')
os.makedirs(BACKUP_FOLDER, exist_ok=True)


def day_backup_folder(date_str):
    """Return the date-specific backup subfolder, e.g. backups/backup-10-04-2026/"""
    folder_name = f"backup-{datetime.strptime(date_str, '%Y-%m-%d').strftime('%d-%m-%Y')}"
    return os.path.join(BACKUP_FOLDER, folder_name)


def is_day_closed(date_str):
    """Return True if a closed backup file exists for this date
    AND the day has not been re-opened."""
    if not date_str:
        return False
    try:
        folder = day_backup_folder(date_str)
        closed_file = os.path.join(folder, f'accounts_{date_str}_closed.db')
        reopened_file = os.path.join(folder, f'accounts_{date_str}_reopened.txt')
        return os.path.exists(closed_file) and not os.path.exists(reopened_file)
    except Exception:
        return False


def is_day_reopened(date_str):
    """Return True if a reopen marker file exists for this date."""
    if not date_str:
        return False
    try:
        folder = day_backup_folder(date_str)
        reopened_file = os.path.join(folder, f'accounts_{date_str}_reopened.txt')
        return os.path.exists(reopened_file)
    except Exception:
        return False


def get_admin_pin_hash(db):
    """Return the stored admin PIN hash, seeding a default of '1234'
    on first use. Stored in the existing settings table — no schema change."""
    row = db.execute('SELECT value FROM settings WHERE key = ?',
                     ('admin_pin_hash',)).fetchone()
    if row and row['value']:
        return row['value']
    default_hash = generate_password_hash('1234', method='pbkdf2:sha256')
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('admin_pin_hash', default_hash))
    db.commit()
    return default_hash


def verify_admin_pin(db, pin):
    """Return True if the supplied PIN matches the stored hash."""
    if not pin:
        return False
    try:
        return check_password_hash(get_admin_pin_hash(db), pin)
    except Exception:
        return False


def set_admin_pin(db, new_pin):
    """Hash and persist a new admin PIN."""
    new_hash = generate_password_hash(new_pin, method='pbkdf2:sha256')
    db.execute('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)',
               ('admin_pin_hash', new_hash))
    db.commit()


def get_reopen_time(date_str):
    """Return the time-of-day of the most recent reopen for this date,
    as a human string like '08:45 PM', by parsing logs/reopen.log.
    Returns None if nothing is found."""
    if not date_str:
        return None
    log_file = os.path.join(BASE_DIR, 'logs', 'reopen.log')
    if not os.path.exists(log_file):
        return None
    try:
        with open(log_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        # Log line format (written by reopen_day):
        #   2026-04-09 08:45 PM — Day 2026-04-09 reopened by admin
        marker = f'Day {date_str} reopened'
        for line in reversed(lines):
            if marker not in line:
                continue
            stamp = line.strip().split(' — ', 1)[0]
            # stamp = "2026-04-09 08:45 PM"  →  "08:45 PM"
            parts = stamp.split(' ')
            if len(parts) >= 3:
                return ' '.join(parts[1:])
            return stamp
    except Exception:
        return None
    return None


@app.route('/backup')
@login_required
def backup():
    """Create a timestamped backup of the database file."""
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    backup_filename = f'backup_{timestamp}.db'
    backup_path = os.path.join(BACKUP_FOLDER, backup_filename)

    try:
        shutil.copy2(DATABASE, backup_path)
        flash(f'Backup created: {backup_filename}', 'success')
    except Exception as e:
        flash(f'Backup failed: {str(e)}', 'error')

    return redirect(url_for('settings'))

def _pdf_styles():
    """Shared PDF styles for all reports — professional business look."""
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_RIGHT

    styles = getSampleStyleSheet()

    BRAND = colors.HexColor('#1a3c5e')
    ACCENT = colors.HexColor('#2980b9')
    LIGHT_BG = colors.HexColor('#f4f7fa')
    GREEN_BG = colors.HexColor('#e8f6ef')
    GREEN_ACCENT = colors.HexColor('#27ae60')
    RED_BG = colors.HexColor('#fbeaea')
    RED_ACCENT = colors.HexColor('#c0392b')
    BORDER = colors.HexColor('#d5dce4')
    TEXT_DARK = colors.HexColor('#2c3e50')
    TEXT_MID = colors.HexColor('#5d6d7e')

    return {
        'base': styles,
        'colors': {
            'brand': BRAND, 'accent': ACCENT, 'light_bg': LIGHT_BG,
            'green_bg': GREEN_BG, 'green_accent': GREEN_ACCENT,
            'red_bg': RED_BG, 'red_accent': RED_ACCENT,
            'border': BORDER, 'text_dark': TEXT_DARK, 'text_mid': TEXT_MID,
        },
        'title': ParagraphStyle(
            'PDFTitle', parent=styles['Title'],
            fontName='Helvetica-Bold', fontSize=22, leading=26,
            textColor=BRAND, spaceAfter=2),
        'subtitle': ParagraphStyle(
            'PDFSub', parent=styles['Normal'],
            fontName='Helvetica', fontSize=11, textColor=TEXT_MID,
            spaceAfter=6),
        'section': ParagraphStyle(
            'PDFSection', parent=styles['Heading2'],
            fontName='Helvetica-Bold', fontSize=13, spaceBefore=20,
            spaceAfter=10, textColor=BRAND,
            borderWidth=0, leftIndent=0),
        'stamp': ParagraphStyle(
            'PDFStamp', parent=styles['Normal'],
            fontName='Helvetica', fontSize=8, textColor=TEXT_MID,
            alignment=TA_CENTER),
        'footer': ParagraphStyle(
            'PDFFooter', parent=styles['Normal'],
            fontName='Helvetica-Oblique', fontSize=7,
            textColor=colors.HexColor('#aab2bd'), alignment=TA_CENTER),
        'balance_label': ParagraphStyle(
            'BalLabel', parent=styles['Normal'],
            fontName='Helvetica', fontSize=10, textColor=TEXT_MID),
        'balance_value': ParagraphStyle(
            'BalValue', parent=styles['Normal'],
            fontName='Helvetica-Bold', fontSize=10, textColor=TEXT_DARK,
            alignment=TA_RIGHT),
    }


def _pdf_entry_table_style(c):
    """Standard table style for entry rows."""
    from reportlab.lib import colors
    from reportlab.platypus import TableStyle
    return TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c['brand']),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (-1, 0), (-1, -1), 12),
        ('LEFTPADDING', (-1, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, 0), 1.2, c['accent']),
        ('LINEBELOW', (0, 1), (-1, -2), 0.4, c['border']),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1),
         [colors.white, c['light_bg']]),
    ])


def _pdf_totals_row_style(bg_color, accent_color):
    """Style for a single-row totals bar."""
    from reportlab.platypus import TableStyle
    return TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), bg_color),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('ALIGN', (-1, 0), (-1, 0), 'RIGHT'),
        ('TOPPADDING', (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 9),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (-1, 0), (-1, 0), 12),
        ('LINEBELOW', (0, 0), (-1, 0), 1.5, accent_color),
    ])


def _pdf_header_block(elements, business_name, report_title, report_subtitle):
    """Add logo + title + subtitle + decorative line to elements list."""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.platypus import Table, TableStyle, Paragraph, Spacer, Image

    s = _pdf_styles()

    logo_path = os.path.join(ASSETS_FOLDER, 'WB_icon_128x128.png')
    if os.path.exists(logo_path):
        logo = Image(logo_path, width=18*mm, height=18*mm)
        title_para = Paragraph(business_name, s['title'])
        sub_para = Paragraph(report_title, s['subtitle'])
        header_table = Table(
            [[logo, [title_para, sub_para]]],
            colWidths=[22*mm, None])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        elements.append(header_table)
    else:
        elements.append(Paragraph(business_name, s['title']))
        elements.append(Paragraph(report_title, s['subtitle']))

    if report_subtitle:
        elements.append(Paragraph(report_subtitle, s['subtitle']))

    divider = Table([['']], colWidths=[170*mm])
    divider.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, 0), 2, s['colors']['accent']),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    elements.append(divider)
    elements.append(Spacer(1, 12))


def _pdf_footer_block(elements, extra_line=None):
    """Add generation timestamp and branding footer."""
    from reportlab.platypus import Spacer, Paragraph, Table, TableStyle
    from reportlab.lib.units import mm

    s = _pdf_styles()

    elements.append(Spacer(1, 20))

    if extra_line:
        elements.append(Paragraph(extra_line, s['stamp']))
        elements.append(Spacer(1, 6))

    divider = Table([['']], colWidths=[170*mm])
    divider.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (-1, 0), 0.5, s['colors']['border']),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    elements.append(divider)
    elements.append(Spacer(1, 6))

    gen_time = datetime.now().strftime('%d %B %Y, %I:%M %p')
    elements.append(Paragraph(
        f'Generated on {gen_time} &bull; Waqar &amp; Brothers Daily Account Book',
        s['footer']))


def _pdf_summary_table(summary_rows, c):
    """Build styled summary table. Last row gets brand highlight."""
    from reportlab.lib import colors
    from reportlab.platypus import Table, TableStyle
    st = Table(summary_rows, colWidths=[330, 120])
    st.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -2), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -2), 10),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, -1), (-1, -1), 12),
        ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
        ('TOPPADDING', (0, 0), (-1, -2), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -2), 8),
        ('TOPPADDING', (0, -1), (-1, -1), 10),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (-1, 0), (-1, -1), 12),
        ('LEFTPADDING', (-1, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -2), 0.4, c['border']),
        ('BACKGROUND', (0, -1), (-1, -1), c['brand']),
        ('TEXTCOLOR', (0, -1), (-1, -1), colors.white),
        ('LINEBELOW', (0, -1), (-1, -1), 2, c['accent']),
    ]))
    return st


class _NumberedCanvas:
    """Canvas wrapper that renders 'Page X of Y' on every page."""

    @staticmethod
    def make(brand_hex='#5d6d7e'):
        from reportlab.pdfgen import canvas as pdf_canvas
        from reportlab.lib.units import mm
        from reportlab.lib import colors

        color = colors.HexColor(brand_hex)

        class Numbered(pdf_canvas.Canvas):
            def __init__(self, *args, **kwargs):
                pdf_canvas.Canvas.__init__(self, *args, **kwargs)
                self._saved_page_states = []

            def showPage(self):
                self._saved_page_states.append(dict(self.__dict__))
                self._startPage()

            def save(self):
                total = len(self._saved_page_states)
                for state in self._saved_page_states:
                    self.__dict__.update(state)
                    self._draw_watermark()
                    self._draw_page_number(total)
                    pdf_canvas.Canvas.showPage(self)
                pdf_canvas.Canvas.save(self)

            def _draw_watermark(self):
                self.saveState()
                self.setFont('Helvetica-Bold', 48)
                self.setFillColorRGB(0.92, 0.93, 0.95, alpha=0.35)
                w, h = self._pagesize
                self.translate(w / 2, h / 2)
                self.rotate(45)
                self.drawCentredString(0, 0, 'Waqar Brothers')
                self.restoreState()

            def _draw_page_number(self, total):
                self.setFont('Helvetica', 8)
                self.setFillColor(color)
                self.drawRightString(
                    self._pagesize[0] - 20*mm, 10*mm,
                    f'Page {self._pageNumber} of {total}')

        return Numbered


def _build_pdf_document(elements):
    """Build a ReportLab PDF in memory and return BytesIO at position 0."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate

    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=A4,
                             leftMargin=20*mm, rightMargin=20*mm,
                             topMargin=18*mm, bottomMargin=18*mm)
    doc.build(elements, canvasmaker=_NumberedCanvas.make())
    output.seek(0)
    return output


def _build_daily_pdf_bytes(db, date_str):
    """Build a Daily Closing Report PDF for the given date.
    Returns a BytesIO positioned at 0. Raises on failure.

    This is a small helper for Close Day — it is independent of the
    existing /export/pdf route so that route's logic stays untouched.
    """
    from reportlab.lib import colors
    from reportlab.platypus import Table, Paragraph, Spacer

    s = _pdf_styles()
    c = s['colors']

    report_date = date.fromisoformat(date_str)
    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'
    opening_balance = get_opening_balance(db, date_str)

    recoveries = db.execute('''
        SELECT description, amount
        FROM daily_entries
        WHERE date = ? AND type = 'recovery' AND is_deleted = 0
        ORDER BY id ASC
    ''', (date_str,)).fetchall()

    expenses = db.execute('''
        SELECT description, amount
        FROM daily_entries
        WHERE date = ? AND type = 'expense' AND is_deleted = 0
        ORDER BY id ASC
    ''', (date_str,)).fetchall()

    total_recovery = sum(r['amount'] for r in recoveries)
    total_expenses = sum(e['amount'] for e in expenses)
    closing_balance = opening_balance + total_recovery - total_expenses

    entry_ts = _pdf_entry_table_style(c)

    elements = []

    _pdf_header_block(elements, business_name,
                      f'Daily Closing Report &mdash; {report_date.strftime("%d %B %Y")}',
                      None)

    # Opening balance badge
    ob_data = [['Opening Balance', format_pkr(opening_balance)]]
    ob = Table(ob_data, colWidths=[330, 120])
    ob.setStyle(_pdf_totals_row_style(c['light_bg'], c['border']))
    elements.append(ob)
    elements.append(Spacer(1, 14))

    # Recovery section
    elements.append(Paragraph('Recovery Entries', s['section']))
    if recoveries:
        data = [['#', 'Salesman', 'Amount']]
        for i, r in enumerate(recoveries, 1):
            data.append([str(i), r['description'], format_pkr(r['amount'])])
        t = Table(data, colWidths=[30, 300, 120])
        t.setStyle(entry_ts)
        elements.append(t)
    else:
        elements.append(Paragraph('No recovery entries for this day.',
                                   s['base']['Normal']))
    elements.append(Spacer(1, 6))
    tr = Table([['Total Recovery', format_pkr(total_recovery)]],
               colWidths=[330, 120])
    tr.setStyle(_pdf_totals_row_style(c['green_bg'], c['green_accent']))
    elements.append(tr)
    elements.append(Spacer(1, 14))

    # Expense section
    elements.append(Paragraph('Expense Entries', s['section']))
    if expenses:
        data = [['#', 'Description', 'Amount']]
        for i, ex in enumerate(expenses, 1):
            data.append([str(i), ex['description'], format_pkr(ex['amount'])])
        t = Table(data, colWidths=[30, 300, 120])
        t.setStyle(entry_ts)
        elements.append(t)
    else:
        elements.append(Paragraph('No expense entries for this day.',
                                   s['base']['Normal']))
    elements.append(Spacer(1, 6))
    te = Table([['Total Expenses', format_pkr(total_expenses)]],
               colWidths=[330, 120])
    te.setStyle(_pdf_totals_row_style(c['red_bg'], c['red_accent']))
    elements.append(te)
    elements.append(Spacer(1, 18))

    # Summary
    elements.append(Paragraph('Summary', s['section']))
    summary_data = [
        ['Opening Balance', format_pkr(opening_balance)],
        ['+ Total Recovery', format_pkr(total_recovery)],
        ['- Total Expenses', format_pkr(total_expenses)],
        ['= Closing Balance', format_pkr(closing_balance)],
    ]
    elements.append(_pdf_summary_table(summary_data, c))

    closed_at = datetime.now().strftime('%d %B %Y, %I:%M %p')
    _pdf_footer_block(elements, extra_line=f'Day closed on {closed_at}')

    return _build_pdf_document(elements)


@app.route('/close-day', methods=['POST'])
@login_required
def close_day():
    db = get_db()
    date_str = request.form.get('date', '').strip()

    if not date_str:
        flash('Invalid date.', 'error')
        return redirect(url_for('daily'))

    # Validate date format
    try:
        date.fromisoformat(date_str)
    except ValueError:
        flash('Invalid date format.', 'error')
        return redirect(url_for('daily'))

    # Ensure date-specific backup folder exists
    day_folder = day_backup_folder(date_str)
    try:
        os.makedirs(day_folder, exist_ok=True)
    except Exception as e:
        flash(f'Could not create backup folder: {e}', 'error')
        return redirect(url_for('daily', date=date_str))

    # Check if already closed (but allow re-close if the day was reopened)
    closed_file = os.path.join(day_folder, f'accounts_{date_str}_closed.db')
    reopened_file = os.path.join(
        day_folder, f'accounts_{date_str}_reopened.txt')

    if os.path.exists(closed_file) and not os.path.exists(reopened_file):
        flash('Day already closed.', 'error')
        return redirect(url_for('daily', date=date_str))

    # If the day had been reopened, clear the reopen marker so the fresh
    # close takes effect. The existing closed.db is simply overwritten
    # below — we never touch historical backups besides this same file.
    if os.path.exists(reopened_file):
        try:
            os.remove(reopened_file)
        except Exception as e:
            flash(f'Could not clear reopen marker: {e}', 'error')
            return redirect(url_for('daily', date=date_str))

    # STEP 1 — create (or overwrite) the closed DB backup
    try:
        shutil.copy2(DATABASE, closed_file)
    except Exception as e:
        flash(f'Error closing day: {str(e)}', 'error')
        return redirect(url_for('daily', date=date_str))

    # STEP 2 — build PDF report (reuses shared helper)
    try:
        pdf_buffer = _build_daily_pdf_bytes(db, date_str)
    except Exception as e:
        flash(f'Day closed but PDF generation failed: {str(e)}', 'error')
        return redirect(url_for('daily', date=date_str))

    # STEP 3 — save PDF to date-specific backup folder
    pdf_filename = f'daily_report_{date_str}.pdf'
    pdf_path = os.path.join(day_folder, pdf_filename)
    try:
        with open(pdf_path, 'wb') as f:
            f.write(pdf_buffer.getvalue())
    except Exception as e:
        # Not fatal — the DB backup is the critical artifact; still download
        flash(f'PDF download ready, but saving to backups failed: {str(e)}',
              'error')

    # STEP 4 — send PDF as download
    pdf_buffer.seek(0)
    return send_file(pdf_buffer,
                     as_attachment=True,
                     download_name=pdf_filename,
                     mimetype='application/pdf')


@app.route('/reopen-day', methods=['POST'])
@login_required
def reopen_day():
    """Re-open a previously closed day so entries can be edited again.
    Does NOT delete or modify the existing closed backup file.
    Creates a marker file accounts_<date>_reopened.txt which is_day_closed()
    checks to decide the editable state."""
    db = get_db()
    date_str = request.form.get('date', '').strip()
    pin = request.form.get('pin', '').strip()

    if not date_str:
        flash('Invalid date.', 'error')
        return redirect(url_for('daily'))

    # Validate date format
    try:
        date.fromisoformat(date_str)
    except ValueError:
        flash('Invalid date format.', 'error')
        return redirect(url_for('daily'))

    # Require a valid 4-digit admin PIN before doing anything else
    if not verify_admin_pin(db, pin):
        flash('Invalid PIN.', 'error')
        return redirect(url_for('daily', date=date_str))

    # Ensure date-specific backup folder exists
    day_folder = day_backup_folder(date_str)
    try:
        os.makedirs(day_folder, exist_ok=True)
    except Exception as e:
        flash(f'Could not access backup folder: {e}', 'error')
        return redirect(url_for('daily', date=date_str))

    # Must have been closed before it can be reopened
    closed_file = os.path.join(
        day_folder, f'accounts_{date_str}_closed.db')
    if not os.path.exists(closed_file):
        flash('This day is not closed, so it cannot be reopened.', 'error')
        return redirect(url_for('daily', date=date_str))

    # Create reopened marker file (safe — never touches the closed.db backup)
    reopened_file = os.path.join(
        day_folder, f'accounts_{date_str}_reopened.txt')

    # Block duplicate reopens
    if os.path.exists(reopened_file):
        flash('Day already reopened.', 'error')
        return redirect(url_for('daily', date=date_str))

    try:
        timestamp = datetime.now().strftime('%Y-%m-%d %I:%M %p')
        user_label = session.get('username', 'unknown')
        with open(reopened_file, 'w', encoding='utf-8') as f:
            f.write(f'Day {date_str} reopened on {timestamp} by {user_label}\n')
    except Exception as e:
        flash(f'Error reopening day: {str(e)}', 'error')
        return redirect(url_for('daily', date=date_str))

    # Append to reopen log
    try:
        logs_folder = os.path.join(BASE_DIR, 'logs')
        os.makedirs(logs_folder, exist_ok=True)
        log_path = os.path.join(logs_folder, 'reopen.log')
        log_stamp = datetime.now().strftime('%Y-%m-%d %I:%M %p')
        with open(log_path, 'a', encoding='utf-8') as f:
            f.write(f'{log_stamp} — Day {date_str} reopened by '
                    f'{session.get("username", "unknown")}\n')
    except Exception:
        # Logging failure must not block the reopen action
        pass

    flash('Day reopened successfully.', 'success')
    return redirect(url_for('daily', date=date_str))


@app.route('/change-pin', methods=['POST'])
@login_required
def change_pin():
    """Change the admin PIN used to authorize Re-open Day.
    Requires the logged-in user's own login password as re-auth —
    this collapses the original two-step flow into one secure POST."""
    db = get_db()
    current_password = request.form.get('current_password', '')
    new_pin = request.form.get('new_pin', '').strip()
    confirm_pin = request.form.get('confirm_pin', '').strip()

    # Re-verify the logged-in user's password
    user = db.execute('SELECT password FROM users WHERE id = ?',
                      (session.get('user_id'),)).fetchone()
    if not user or not check_password_hash(user['password'], current_password):
        flash('Incorrect login password.', 'error')
        return redirect(url_for('settings'))

    # Validate the new PIN
    if not (new_pin.isdigit() and len(new_pin) == 4):
        flash('PIN must be exactly 4 digits.', 'error')
        return redirect(url_for('settings'))

    if new_pin != confirm_pin:
        flash('PINs do not match.', 'error')
        return redirect(url_for('settings'))

    set_admin_pin(db, new_pin)
    flash('PIN updated successfully.', 'success')
    return redirect(url_for('settings'))


# --- Export to PDF ---

@app.route('/export/pdf')
@login_required
def export_pdf():
    """Export daily or monthly report as a downloadable PDF."""
    from reportlab.lib import colors
    from reportlab.platypus import Table, Paragraph, Spacer

    db = get_db()
    today = date.today()
    business_name = get_setting(db, 'business_name') or 'Waqar & Brothers'

    s = _pdf_styles()
    c = s['colors']
    entry_ts = _pdf_entry_table_style(c)

    date_param = request.args.get('date')
    month_param = request.args.get('month')
    year_param = request.args.get('year')

    elements = []

    if date_param:
        # --- DAILY REPORT ---
        try:
            report_date = date.fromisoformat(date_param)
        except ValueError:
            report_date = today
            date_param = today.isoformat()

        display = report_date.strftime('%d %B %Y')
        _pdf_header_block(elements, business_name,
                          f'Daily Report &mdash; {display}', None)

        opening_balance = get_opening_balance(db, date_param)

        # Opening balance badge
        ob = Table([['Opening Balance', format_pkr(opening_balance)]],
                   colWidths=[330, 120])
        ob.setStyle(_pdf_totals_row_style(c['light_bg'], c['border']))
        elements.append(ob)
        elements.append(Spacer(1, 14))

        # INCOME section
        recoveries = db.execute('''
            SELECT description, amount
            FROM daily_entries
            WHERE date = ? AND type = 'recovery' AND is_deleted = 0
            ORDER BY id ASC
        ''', (date_param,)).fetchall()

        elements.append(Paragraph('Income (Recovery)', s['section']))

        if recoveries:
            data = [['#', 'Salesman', 'Amount']]
            for i, r in enumerate(recoveries, 1):
                data.append([str(i), r['description'], format_pkr(r['amount'])])
            t = Table(data, colWidths=[30, 300, 120])
            t.setStyle(entry_ts)
            elements.append(t)

            total_recovery = sum(r['amount'] for r in recoveries)
            tt = Table([['Total Income', format_pkr(total_recovery)]],
                       colWidths=[330, 120])
            tt.setStyle(_pdf_totals_row_style(c['green_bg'], c['green_accent']))
            elements.append(tt)
        else:
            elements.append(Paragraph('No recovery entries.', s['base']['Normal']))
            total_recovery = 0

        elements.append(Spacer(1, 14))

        # EXPENSE section
        expenses = db.execute('''
            SELECT description, amount, payment_type
            FROM daily_entries
            WHERE date = ? AND type = 'expense' AND is_deleted = 0
            ORDER BY id ASC
        ''', (date_param,)).fetchall()

        elements.append(Paragraph('Expenses', s['section']))

        if expenses:
            data = [['#', 'Type', 'Description', 'Amount']]
            for i, e in enumerate(expenses, 1):
                ptype = (e['payment_type'] or 'cash').capitalize()
                data.append([str(i), ptype, e['description'],
                             format_pkr(e['amount'])])
            t = Table(data, colWidths=[30, 80, 220, 120])
            t.setStyle(entry_ts)
            elements.append(t)

            total_expenses = sum(e['amount'] for e in expenses)
            tt = Table([['Total Expenses', format_pkr(total_expenses)]],
                       colWidths=[330, 120])
            tt.setStyle(_pdf_totals_row_style(c['red_bg'], c['red_accent']))
            elements.append(tt)
        else:
            elements.append(Paragraph('No expense entries.', s['base']['Normal']))
            total_expenses = 0

        elements.append(Spacer(1, 18))

        # SUMMARY
        net = opening_balance + total_recovery - total_expenses
        elements.append(Paragraph('Summary', s['section']))
        summary_data = [
            ['Opening Balance', format_pkr(opening_balance)],
            ['+ Total Recovery', format_pkr(total_recovery)],
            ['- Total Expenses', format_pkr(total_expenses)],
            ['= Closing Balance', format_pkr(net)],
        ]
        elements.append(_pdf_summary_table(summary_data, c))

        _pdf_footer_block(elements)
        pdf_filename = f'WaqarBrothers_Daily_{date_param}.pdf'

    else:
        # --- MONTHLY REPORT ---
        try:
            month = int(month_param or today.month)
            year = int(year_param or today.year)
            if not (1 <= month <= 12):
                raise ValueError
        except (ValueError, TypeError):
            month = today.month
            year = today.year

        month_str = str(month).zfill(2)
        year_str = str(year)
        month_label = date(year, month, 1).strftime('%B %Y')

        _pdf_header_block(elements, business_name,
                          f'Monthly Report &mdash; {month_label}', None)

        # Opening balance for the month
        first_of_month = f'{year_str}-{month_str}-01'
        opening_balance = get_opening_balance(db, first_of_month)

        # Fetch all entries for the month grouped by day
        rows = db.execute('''
            SELECT date, type, description, amount, payment_type
            FROM daily_entries
            WHERE strftime('%m', date) = ? AND strftime('%Y', date) = ?
                  AND is_deleted = 0
            ORDER BY date ASC, id ASC
        ''', (month_str, year_str)).fetchall()

        total_income = 0
        total_expense = 0

        if rows:
            data = [['Date', 'Type', 'Description', 'Payment', 'Amount']]
            for row in rows:
                ptype = (row['payment_type'] or 'cash').capitalize()
                entry_type = row['type'].capitalize()
                data.append([
                    row['date'],
                    entry_type,
                    row['description'],
                    ptype,
                    format_pkr(row['amount']),
                ])
                if row['type'] == 'recovery':
                    total_income += row['amount']
                else:
                    total_expense += row['amount']

            t = Table(data, colWidths=[70, 65, 170, 65, 100])
            t.setStyle(entry_ts)
            elements.append(t)
        else:
            elements.append(Paragraph('No entries for this month.',
                                       s['base']['Normal']))

        elements.append(Spacer(1, 18))

        # SUMMARY
        net = opening_balance + total_income - total_expense
        elements.append(Paragraph('Summary', s['section']))
        summary_data = [
            ['Opening Balance', format_pkr(opening_balance)],
            ['Total Income', format_pkr(total_income)],
            ['Total Expenses', format_pkr(total_expense)],
            ['Closing Balance', format_pkr(net)],
        ]
        elements.append(_pdf_summary_table(summary_data, c))

        _pdf_footer_block(elements)
        month_short = date(year, month, 1).strftime('%b')
        pdf_filename = f'WaqarBrothers_{month_short}_{year}.pdf'

    output = _build_pdf_document(elements)

    return send_file(output,
                     as_attachment=True,
                     download_name=pdf_filename,
                     mimetype='application/pdf')


# --- Run the App ---

def open_browser():
    """Open the app in the default browser after a short delay."""
    webbrowser.open('http://127.0.0.1:8000')


if __name__ == '__main__':
    Timer(1, open_browser).start()
    app.run(host='127.0.0.1', port=8000, debug=False, use_reloader=False)
